Some changes, including DNS support
key-networks/ztncui pull request #57
Opened 2021-02-18 05:49 UTC by lideming

### Added DNS setting support

* API references:
  + https://github.com/zerotier/ZeroTierOne/blob/e8390afad5ca119e603d342af25b349fd584f77f/controller/EmbeddedNetworkController.cpp#L1032
  + https://github.com/zerotier/ZeroTierOne/blob/e8390afad5ca119e603d342af25b349fd584f77f/controller/EmbeddedNetworkController.cpp#L1710

![image](https://user-images.githubusercontent.com/14901890/108306703-b734b180-71e7-11eb-8a74-26589b33433a.png)

### Now the `network_detail` page looks like this:

![image](https://user-images.githubusercontent.com/14901890/108306448-1f36c800-71e7-11eb-8b88-86c30bbee8dc.png)
* That "Name" form looks too bad. Unfortunately I don't have a better design yet...
* `members` and `name` pages are removed.
* Links to `[nwid]/members` are replaced by `[nwid]#members`.
* Yeah maybe we need to update README accordingly...

### Trivial
* Removed the usage of CDN since it's very slow when accessing from China.
* Fixed error trying to read TLS cert files when the server was configured to use HTTP (without S).
* Refactored some layout files to removed duplicated header/navbar code.
* Now it will get network members detail in parallel. This save some time (50 -> 30 ms) when my machine handle a page with 30 network members.

### By the way
`npm start` doesn't start the server with production mode, causing the template engine always re-compile the pug file when rendering (taking ~200 ms!). We should start the server with `NODE_ENV=production`. (Mention this in README?)
(See: https://pugjs.org/api/express.html)

---
I've been using ztncui for a year. Thank you for this project!
If some of these changes are unacceptable, please tell me :)

2021-02-19 06:24 UTC, drtech981 commented
Feature Request : Hi, I see you have done an awesome job of implementing a ton of additional features to the ZTN-CUI base, but could you also try and add the following features ?
1. Member Status (Online/Offline)
2. Member Last Seen 
3. Member Physical IP
4. Member Description
5. Member MAC Address
These features are really handy while diagnosing and troubleshooting problems, and as such would be a great addition to the controller UI.

2021-02-19 07:02 UTC, lideming commented
Hi @drtech981,
For member **status**, **last seen**, **physical IP**, **MAC** , I wanted to add them too. Unfortunately, these info are just not provided on the ZT controller API but [ZT Central API](https://my.zerotier.com/central-api.html#member-member-get) (I guess these info are only available on ZT roots but not controllers). So it's implementable, but need to access ZT Central API, which required an API token.

Member **description** is easier to implement.

There are more features that I want to add:
* Per network member name (with an option to enable/disable this feature)
* Rules editor
  + Capabilities and tags selector for members
* Network ownership (currently all admins can manage all networks)

2021-02-20 07:53 UTC, key-networks requested changes
@lideming I really like what you have done!  I've left a few comments and look forward to working with you to improve ztncui.

2021-02-20 07:53 UTC, key-networks commented on src/views/network_detail.pug
> +          button.btn.btn-primary(type='submit') Submit
One option is to use the same jquery technique that is used for naming/renaming members to submit a change to the network name.

2021-02-20 07:53 UTC, key-networks commented on src/views/dns.pug
> +            li!= err.msg
It would be good, for the sake of consistency with the rest of the pages that implement changes to network settings, if you could display the existing DNS settings (if any) and then the newly submitted settings above the input boxes - see ipAssignmentPools as an example.  With the current implementation, there is no immediate feedback to the user when they click Submit, so it might lead to a bit of confusion.

2021-02-20 07:53 UTC, key-networks commented on src/views/head_layout.pug
> +    script(src='/jqjs/jquery.min.js')
The reason I had to revert to using a CDN was because of a bug in pkg - see here https://github.com/key-networks/ztncui/issues/30

Are you using ztncui directly from source?  If so, I wonder if there is a way that we can get around this problem because I agree that it would be better to use the embedded jquery.

2021-02-20 07:53 UTC, key-networks commented on src/views/network_detail.pug
>      a.btn.btn-default(href='/controller/networks' name='networks' role='button') Networks
I wonder if we can somehow increase the space above this button?  In my browser it is touching the bottom of the word 'v6AssignMode'

2021-02-20 07:53 UTC, key-networks commented on src/package.json
> +    "jquery": "~3.4.1",
I noticed that npm gave a security warning for 3.4.1.  What was the issue with 3.5.1?

2021-02-20 21:24 UTC, lideming commented on src/package.json
> +    "jquery": "~3.4.1",
jQuery 3.5 breaks Bootstrap navbar collapse. It was fixed on Bootstrap v4 but not on v3 (https://github.com/twbs/bootstrap/issues/30553).

2021-02-20 23:23 UTC, lideming commented on src/views/head_layout.pug
> +    script(src='/jqjs/jquery.min.js')
It's really weird that why this only happen to jquery while other assets just work well...

2021-02-21 06:55 UTC, lideming commented
## New renaming UI:
1) Click the title on the network detail page:
![image](https://user-images.githubusercontent.com/14901890/108617880-873e1600-7454-11eb-86e1-a0f1552b24a0.png)

---
2) Edit then press Enter or focusout:
![image](https://user-images.githubusercontent.com/14901890/108617887-945b0500-7454-11eb-86d6-e87aa643f86b.png)

---
3) The title will update when the post succeed:
![image](https://user-images.githubusercontent.com/14901890/108617788-0da62800-7454-11eb-8190-c405b3a36a2b.png)

2021-02-21 11:19 UTC, key-networks reviewed
@lideming thanks for your changes.  I tested them and they seem to be good.  I am trying to build an rpm and deb package to make available to others for testing, but am having trouble with pkg.  Will let you know once I've got it sorted out.

2021-02-22 05:58 UTC, lideming commented
@key-networks 
After trying with pkg, I know why it doesn't include the jquery.min.js in the build...
It seems that pkg will look into the `package.json` of required modules.
Some assets (e.g. Bootstrap) have included the "dist" folder in the "files" list in `package.json`, but it's not the case of jquery...

2021-02-22 11:56 UTC, key-networks commented
Good find, @lideming !

2021-02-22 12:35 UTC, key-networks approved these changes

2021-02-22 13:03 UTC, key-networks commented
ztncui-0.6.8-1.x86_64.rpm and ztncui_0.6.8_amd64.deb have been built based on this PR.  They are available at https://s3-us-west-1.amazonaws.com/key-networks/deb/ztncui/1/x86_64/ztncui_0.6.8_amd64.deb for Debian/Ubuntu or can be installed on RedHat derivatives with:
`sudo yum --enablerepo=ztncui-testing install ztncui`

Could somebody please test one or both and give feedback on the UI changes?

2021-02-22 16:21 UTC, Fastidious commented
Will test in a short bit.

2021-02-22 17:21 UTC, Fastidious commented
@key-networks, it works lovely!

2021-02-22 22:31 UTC, key-networks commented
Thanks @Fastidious for testing and for your feedback!

2021-02-24 05:54 UTC, lideming commented
## Now we have peer status / address / latency! 😄
![image](https://user-images.githubusercontent.com/14901890/108954109-3e31d000-76a7-11eb-9c52-dc3be57c6f96.png)

2021-02-24 06:38 UTC, lideming commented
I have finished adding features into this PR.

2021-02-24 07:53 UTC, drtech981 commented
> ## Now we have peer status / address / latency! 😄
> ![image](https://user-images.githubusercontent.com/14901890/108954109-3e31d000-76a7-11eb-9c52-dc3be57c6f96.png)

This looks awesome !!! Now I believe ZTN-CUI has almost all the features of ZeroTier Central UI !!

It would be great if you could also add Descriptions for networks as well as members, since it is very helpful to maintain large networks.

2021-02-24 10:33 UTC, ali-95 commented
> ## Now we have peer status / address / latency! 😄

and how to install it?

2021-02-24 10:56 UTC, lideming commented
> and how to install it?

Please wait for the release.

2021-02-24 11:03 UTC, lideming commented
> It would be great if you could also add Descriptions for networks as well as members, since it is very helpful to maintain large networks.

That should be another PR, since this PR have made too many changes.

2021-02-24 13:21 UTC, key-networks commented
@lideming thank you for your excellent contributions!

2021-02-24 13:26 UTC, key-networks commented
To everyone else, new packages including @lideming 's latest commits have been built and are available at https://s3-us-west-1.amazonaws.com/key-networks/deb/ztncui/1/x86_64/ztncui_0.6.9_amd64.deb for Debian/Ubuntu or can be installed on Redhat derivatives with:
`sudo yum --enablerepo=ztncui-testing install ztncui`

Please note that these packages are provided 'as is' without an in-depth examination of the latest code - please feel free to examine the code in this PR and give your comments/feedback - these packages are provided purely for testing.

2021-02-24 14:17 UTC, ali-95 commented
> `sudo yum --enablerepo=ztncui-testing install ztncui`

I have version 0.6.8 installed how do I update it to 0.6.9
у меня установлена версия ztncui_0.6.8 как ее обновить до 0.6.9

2021-02-24 17:14 UTC, Fastidious commented
@key-networks testing it in a bit.

2021-02-24 17:21 UTC, Fastidious commented
@key-networks no issues. Great job!

2021-02-24 18:07 UTC, ali-95 commented
> 
> 
> > `sudo yum --enablerepo=ztncui-testing install ztncui`
> 
> I have version 0.6.8 installed how do I update it to 0.6.9
> у меня установлена версия ztncui_0.6.8 как ее обновить до 0.6.9

у меня тоже все работает, нужно было удалить старую версию и потом по новой установить 0,6,9

2021-02-24 22:08 UTC, Fastidious commented
@ali-95 weird. A simple ‘apt install file.deb’ did it for me. Went from .6.8 to .6.9.

2021-02-25 10:03 UTC, key-networks commented
Thanks for your feedback, @Fastidious and @ali-95.  The credit for the new work goes to @lideming.  I'm hoping to have some time this weekend to review the latest code changes and look at merging into master before producing a final build as well as an updated Docker image.

2021-02-25 22:26 UTC, kbarlee commented
All works well for me! The client version info is quite interesting -  found a couple of boxes that didn't want to apt update to latest version automatically. Going to try out the DNS stuff in the next few days.

2021-02-27 01:55 UTC, key-networks commented
Thanks for your feedback @kbarlee!

2021-02-27 10:55 UTC, jimthedj65 commented
Hi, all I upgraded with 0.6.8 and all running great and looks very stable. I will now update to 0.6.9
Installed on baremetal version Linux vpp-dev-baremetal01 4.15.0-135-generic #139-Ubuntu SMP Mon Jan 18 17:38:24 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

`sudo dpkg -i ztncui_0.6.8_amd64.deb
(Reading database ... 299122 files and directories currently installed.)
Preparing to unpack ztncui_0.6.8_amd64.deb ...
Unpacking ztncui (0.6.8) over (0.6.4) ...
Setting up ztncui (0.6.8) ...
TLS key and certificate already exist`

redirected to ztncui='ssh -p 5699 -f ztncuiname@xx.xx.xx.xx -L 3333:localhost:3000 -N'

Success logged in and works like a charm.

2021-02-27 10:58 UTC, jimthedj65 commented
Just upgraded to 0.6.9 and absolutely love the information presented, flawless update 
`Preparing to unpack ztncui_0.6.9_amd64.deb ...
Unpacking ztncui (0.6.9) over (0.6.8) ...
Setting up ztncui (0.6.9) ...
TLS key and certificate already exist`

Thank you for the changes, it helps a lot.

2021-03-01 01:16 UTC, key-networks commented
@jimthedj65 - thanks for your feedback!

2021-03-01 03:30 UTC, key-networks commented
@lideming - I've made some changes (doc updates, etc), but I don't have rights to push to your fork, so made a branch here https://github.com/key-networks/ztncui/tree/pr which incorporates the changes I want to make on top of your changes.  I'm not sure how to make code changes to your PR, but want to continue with your existing PR because of the comment history.  If you can tell me how I can push my commits to your repo, please let me know, otherwise maybe you can pull my commits into your fork?  Thanks!

2021-03-01 03:40 UTC, lideming commented
@key-networks 
You should have the permission to push, since this switch is enabled by default:
![image](https://user-images.githubusercontent.com/14901890/109449040-6b54f880-7a82-11eb-917c-e0f3d34996fa.png)

I think this should work:
```shell
git push https://github.com/lideming/ztncui.git pr
```

2021-03-01 04:27 UTC, key-networks commented
Ok, that worked - thanks for your help!

2021-03-01 04:29 UTC, key-networks commented
Let me know if you have any comments on my commits.

2021-03-01 04:49 UTC, lideming commented
It looks good, thanks!

2021-03-01 07:10 UTC, merged

2021-03-01 07:15 UTC, key-networks commented
Thanks again for your excellent contributions, @lideming !